version: '3'

services:
  db:
    image: mongo:latest
    volumes: 
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: default
    ports:
      - "27017:27017"
    networks:
      - app-network

  app:
    depends_on:
      - db
    build: ./docker/php
    container_name: app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - app
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
     - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis:/data

volumes:
  mongodb:
  mongodb_config:
  redis:

networks:
  app-network:
    driver: bridge