version: '3'

services:
  db:
    image: mongo:latest
    volumes: 
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: default
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  app:
    depends_on:
      - db
    build: .
    container_name: app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - app
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge